language: java
jdk:
  - openjdk17

# Indica que estamos usando o sistema de compilação Maven
script:
  - ./mvnw.cmd install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# Você pode adicionar etapas adicionais, como testes, aqui
# Por exemplo, para executar os testes após a compilação:
# script:
#   - ./mvnw clean install
#   - ./mvnw test
