language: java
sudo: true
jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "robinhosztravis"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage


before_install:
  - chmod +x mvnw

