language: java
jdk:
  - openjdk17

# Indica que estamos usando o sistema de compilação Maven
script:
- ./mvnw clean install -B

# Você pode adicionar etapas adicionais, como testes, aqui
# Por exemplo, para executar os testes após a compilação:
# script:
#   - ./mvnw clean install
#   - ./mvnw test
