language: java
sudo: true
jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "robinhosztravis"
    token:
      secure: "4f764d5378fa54fc6a984bb8afc04a0c43b35762" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=robinhosztravis_robinhosz


before_install:
  - chmod +x mvnw

